// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Templanza.Data;

#nullable disable

namespace Templanza.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260902145837_AgregarImagenesPlantas")]
    partial class AgregarImagenesPlantas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Templanza.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Templanza.Models.Blend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EsPublicado")
                        .HasColumnType("bit");

                    b.Property<bool>("EsRecomendado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EsPublicado", "EsRecomendado");

                    b.ToTable("Blends");
                });

            modelBuilder.Entity("Templanza.Models.BlendLike", b =>
                {
                    b.Property<int>("BlendId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("BlendId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("BlendLikes");
                });

            modelBuilder.Entity("Templanza.Models.BlendPlanta", b =>
                {
                    b.Property<int>("BlendId")
                        .HasColumnType("int");

                    b.Property<int>("PlantaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("BlendId", "PlantaId");

                    b.HasIndex("PlantaId");

                    b.ToTable("BlendPlantas");
                });

            modelBuilder.Entity("Templanza.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Hierbas que favorecen la digestión",
                            Nombre = "Digestivas"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Hierbas con efecto calmante",
                            Nombre = "Relajantes"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Hierbas estimulantes",
                            Nombre = "Energizantes"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Hierbas depurativas y diuréticas",
                            Nombre = "Depurativas"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Flores e infusiones aromáticas",
                            Nombre = "Florales y aromáticas"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Hierbas que refuerzan las defensas",
                            Nombre = "Inmunológicas"
                        });
                });

            modelBuilder.Entity("Templanza.Models.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlendId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BlendId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Templanza.Models.CorreoEnviado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Cuerpo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("Exito")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CorreosEnviados");
                });

            modelBuilder.Entity("Templanza.Models.Efecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Efectos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Induce calma y reduce el estrés",
                            Nombre = "Relajante"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Favorece la digestión",
                            Nombre = "Digestivo"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Aumenta la energía y el estado de alerta",
                            Nombre = "Estimulante"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Reduce inflamación",
                            Nombre = "Antiinflamatorio"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Favorece la eliminación de líquidos",
                            Nombre = "Diurético"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Refuerza las defensas del organismo",
                            Nombre = "Inmunoestimulante"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Ayuda a combatir el daño celular",
                            Nombre = "Antioxidante"
                        });
                });

            modelBuilder.Entity("Templanza.Models.ItemOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<int>("PlantaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.HasIndex("PlantaId");

                    b.ToTable("ItemOrdenes");
                });

            modelBuilder.Entity("Templanza.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Templanza.Models.Planta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Contraindicaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NombreCientifico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreComun")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Origen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ParteUsada")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Plantas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 2,
                            Contraindicaciones = "Alergia a plantas de la familia Asteraceae",
                            ImagenUrl = "/images/plantas/manzanilla.webp",
                            NombreCientifico = "Matricaria chamomilla",
                            NombreComun = "Manzanilla",
                            Origen = "Europa",
                            ParteUsada = "Flor",
                            Precio = 850m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Contraindicaciones = "Reflujo gastroesofágico",
                            ImagenUrl = "/images/plantas/menta.webp",
                            NombreCientifico = "Mentha spicata",
                            NombreComun = "Menta",
                            Origen = "Asia",
                            ParteUsada = "Hoja",
                            Precio = 700m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Contraindicaciones = "Cálculos biliares",
                            ImagenUrl = "/images/plantas/jengibre.webp",
                            NombreCientifico = "Zingiber officinale",
                            NombreComun = "Jengibre",
                            Origen = "Sudeste asiático",
                            ParteUsada = "Raíz",
                            Precio = 950m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 4,
                            Contraindicaciones = "Obstrucción de vías biliares",
                            ImagenUrl = "/images/plantas/diente-de-leon.webp",
                            NombreCientifico = "Taraxacum officinale",
                            NombreComun = "Diente de león",
                            Origen = "Europa",
                            ParteUsada = "Raíz y hoja",
                            Precio = 780m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Contraindicaciones = "Sensibilidad a la cafeína, insomnio",
                            ImagenUrl = "/images/plantas/te-verde.webp",
                            NombreCientifico = "Camellia sinensis",
                            NombreComun = "Té verde",
                            Origen = "China",
                            ParteUsada = "Hoja",
                            Precio = 1100m,
                            Stock = 140
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            Contraindicaciones = "Sensibilidad a la cafeína, hipertensión",
                            ImagenUrl = "/images/plantas/te-negro.webp",
                            NombreCientifico = "Camellia sinensis",
                            NombreComun = "Té negro",
                            Origen = "China",
                            ParteUsada = "Hoja",
                            Precio = 1050m,
                            Stock = 130
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 3,
                            Contraindicaciones = "Sensibilidad a la cafeína",
                            ImagenUrl = "/images/plantas/te-blanco.webp",
                            NombreCientifico = "Camellia sinensis",
                            NombreComun = "Té blanco",
                            Origen = "China",
                            ParteUsada = "Brote y hoja joven",
                            Precio = 1350m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 3,
                            Contraindicaciones = "Sensibilidad a la cafeína",
                            ImagenUrl = "/images/plantas/te-oolong.webp",
                            NombreCientifico = "Camellia sinensis",
                            NombreComun = "Té oolong",
                            Origen = "China",
                            ParteUsada = "Hoja",
                            Precio = 1200m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 2,
                            Contraindicaciones = "Sin contraindicaciones relevantes conocidas",
                            ImagenUrl = "/images/plantas/rooibos.webp",
                            NombreCientifico = "Aspalathus linearis",
                            NombreComun = "Rooibos",
                            Origen = "Sudáfrica",
                            ParteUsada = "Hoja",
                            Precio = 900m,
                            Stock = 110
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 4,
                            Contraindicaciones = "Embarazo, presión arterial baja",
                            ImagenUrl = "/images/plantas/hibisco.webp",
                            NombreCientifico = "Hibiscus sabdariffa",
                            NombreComun = "Hibisco",
                            Origen = "África",
                            ParteUsada = "Flor (cáliz)",
                            Precio = 820m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 2,
                            Contraindicaciones = "Somnolencia, combinar con sedantes",
                            ImagenUrl = "/images/plantas/lavanda.webp",
                            NombreCientifico = "Lavandula angustifolia",
                            NombreComun = "Lavanda",
                            Origen = "Región mediterránea",
                            ParteUsada = "Flor",
                            Precio = 880m,
                            Stock = 90
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 1,
                            Contraindicaciones = "Uso excesivo en niños pequeños",
                            ImagenUrl = "/images/plantas/anis-estrella.webp",
                            NombreCientifico = "Illicium verum",
                            NombreComun = "Anís estrella",
                            Origen = "China",
                            ParteUsada = "Fruto",
                            Precio = 990m,
                            Stock = 65
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 1,
                            Contraindicaciones = "Embarazo en altas dosis, trastornos hepáticos",
                            ImagenUrl = "/images/plantas/canela.webp",
                            NombreCientifico = "Cinnamomum verum",
                            NombreComun = "Canela",
                            Origen = "Sri Lanka",
                            ParteUsada = "Corteza",
                            Precio = 850m,
                            Stock = 120
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 1,
                            Contraindicaciones = "Cálculos biliares",
                            ImagenUrl = "/images/plantas/cardomomo.webp",
                            NombreCientifico = "Elettaria cardamomum",
                            NombreComun = "Cardamomo",
                            Origen = "India",
                            ParteUsada = "Semilla",
                            Precio = 1150m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 1,
                            Contraindicaciones = "Trastornos de la coagulación",
                            ImagenUrl = "/images/plantas/clavo-de-olor.webp",
                            NombreCientifico = "Syzygium aromaticum",
                            NombreComun = "Clavo de olor",
                            Origen = "Indonesia",
                            ParteUsada = "Botón floral",
                            Precio = 980m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 4,
                            Contraindicaciones = "Cálculos biliares, anticoagulantes",
                            ImagenUrl = "/images/plantas/curcuma.webp",
                            NombreCientifico = "Curcuma longa",
                            NombreComun = "Cúrcuma",
                            Origen = "India",
                            ParteUsada = "Rizoma",
                            Precio = 920m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 1,
                            Contraindicaciones = "Hipertensión, embarazo",
                            ImagenUrl = "/images/plantas/regaliz.webp",
                            NombreCientifico = "Glycyrrhiza glabra",
                            NombreComun = "Regaliz",
                            Origen = "Europa y Asia",
                            ParteUsada = "Raíz",
                            Precio = 860m,
                            Stock = 70
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 2,
                            Contraindicaciones = "Hipotiroidismo",
                            ImagenUrl = "/images/plantas/melisa.webp",
                            NombreCientifico = "Melissa officinalis",
                            NombreComun = "Melisa (Toronjil)",
                            Origen = "Europa",
                            ParteUsada = "Hoja",
                            Precio = 780m,
                            Stock = 95
                        },
                        new
                        {
                            Id = 19,
                            CategoriaId = 2,
                            Contraindicaciones = "Combinar con sedantes o alcohol",
                            ImagenUrl = "/images/plantas/valeriana.webp",
                            NombreCientifico = "Valeriana officinalis",
                            NombreComun = "Valeriana",
                            Origen = "Europa y Asia",
                            ParteUsada = "Raíz",
                            Precio = 940m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 20,
                            CategoriaId = 2,
                            Contraindicaciones = "Embarazo, combinar con sedantes",
                            ImagenUrl = "/images/plantas/pasiflora.webp",
                            NombreCientifico = "Passiflora incarnata",
                            NombreComun = "Pasiflora",
                            Origen = "América",
                            ParteUsada = "Hoja y flor",
                            Precio = 830m,
                            Stock = 75
                        },
                        new
                        {
                            Id = 21,
                            CategoriaId = 2,
                            Contraindicaciones = "Uso prolongado sin supervisión",
                            ImagenUrl = "/images/plantas/tilo.webp",
                            NombreCientifico = "Tilia platyphyllos",
                            NombreComun = "Tilo",
                            Origen = "Europa",
                            ParteUsada = "Flor",
                            Precio = 750m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 22,
                            CategoriaId = 1,
                            Contraindicaciones = "Obstrucción de vías biliares, embarazo",
                            ImagenUrl = "/images/plantas/boldo.webp",
                            NombreCientifico = "Peumus boldus",
                            NombreComun = "Boldo",
                            Origen = "Chile",
                            ParteUsada = "Hoja",
                            Precio = 800m,
                            Stock = 65
                        },
                        new
                        {
                            Id = 23,
                            CategoriaId = 2,
                            Contraindicaciones = "Sin contraindicaciones relevantes conocidas",
                            ImagenUrl = "/images/plantas/cedron.webp",
                            NombreCientifico = "Aloysia citrodora",
                            NombreComun = "Cedrón",
                            Origen = "Sudamérica",
                            ParteUsada = "Hoja",
                            Precio = 720m,
                            Stock = 85
                        },
                        new
                        {
                            Id = 24,
                            CategoriaId = 4,
                            Contraindicaciones = "Insuficiencia renal o cardíaca",
                            ImagenUrl = "/images/plantas/ortiga.webp",
                            NombreCientifico = "Urtica dioica",
                            NombreComun = "Ortiga",
                            Origen = "Europa",
                            ParteUsada = "Hoja",
                            Precio = 690m,
                            Stock = 80
                        },
                        new
                        {
                            Id = 25,
                            CategoriaId = 6,
                            Contraindicaciones = "Enfermedades autoinmunes",
                            ImagenUrl = "/images/plantas/equinacea.webp",
                            NombreCientifico = "Echinacea purpurea",
                            NombreComun = "Equinácea",
                            Origen = "Norteamérica",
                            ParteUsada = "Raíz y flor",
                            Precio = 1000m,
                            Stock = 55
                        },
                        new
                        {
                            Id = 26,
                            CategoriaId = 3,
                            Contraindicaciones = "Embarazo en altas dosis, epilepsia",
                            ImagenUrl = "/images/plantas/romero.webp",
                            NombreCientifico = "Rosmarinus officinalis",
                            NombreComun = "Romero",
                            Origen = "Región mediterránea",
                            ParteUsada = "Hoja",
                            Precio = 760m,
                            Stock = 110
                        },
                        new
                        {
                            Id = 27,
                            CategoriaId = 5,
                            Contraindicaciones = "Sin contraindicaciones relevantes conocidas",
                            ImagenUrl = "/images/plantas/jazmin.webp",
                            NombreCientifico = "Jasminum officinale",
                            NombreComun = "Jazmín",
                            Origen = "Asia",
                            ParteUsada = "Flor",
                            Precio = 950m,
                            Stock = 60
                        },
                        new
                        {
                            Id = 28,
                            CategoriaId = 6,
                            Contraindicaciones = "Cálculos renales",
                            ImagenUrl = "/images/plantas/rosa-mosqueta.webp",
                            NombreCientifico = "Rosa canina",
                            NombreComun = "Rosa mosqueta (Escaramujo)",
                            Origen = "Europa",
                            ParteUsada = "Fruto",
                            Precio = 1080m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 29,
                            CategoriaId = 3,
                            Contraindicaciones = "Hipertensión, insomnio",
                            ImagenUrl = "/images/plantas/ginseng.webp",
                            NombreCientifico = "Panax ginseng",
                            NombreComun = "Ginseng",
                            Origen = "Asia",
                            ParteUsada = "Raíz",
                            Precio = 1450m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 30,
                            CategoriaId = 3,
                            Contraindicaciones = "Sensibilidad a la cafeína, hipertensión",
                            ImagenUrl = "/images/plantas/yerba-mate.webp",
                            NombreCientifico = "Ilex paraguariensis",
                            NombreComun = "Yerba mate",
                            Origen = "Sudamérica",
                            ParteUsada = "Hoja",
                            Precio = 700m,
                            Stock = 150
                        });
                });

            modelBuilder.Entity("Templanza.Models.PlantaEfecto", b =>
                {
                    b.Property<int>("PlantaId")
                        .HasColumnType("int");

                    b.Property<int>("EfectoId")
                        .HasColumnType("int");

                    b.Property<int>("Intensidad")
                        .HasColumnType("int");

                    b.HasKey("PlantaId", "EfectoId");

                    b.HasIndex("EfectoId");

                    b.ToTable("PlantaEfectos");

                    b.HasData(
                        new
                        {
                            PlantaId = 1,
                            EfectoId = 1,
                            Intensidad = 4
                        },
                        new
                        {
                            PlantaId = 2,
                            EfectoId = 2,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 3,
                            EfectoId = 2,
                            Intensidad = 4
                        },
                        new
                        {
                            PlantaId = 3,
                            EfectoId = 3,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 4,
                            EfectoId = 5,
                            Intensidad = 4
                        },
                        new
                        {
                            PlantaId = 5,
                            EfectoId = 3,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 5,
                            EfectoId = 7,
                            Intensidad = 4
                        },
                        new
                        {
                            PlantaId = 6,
                            EfectoId = 3,
                            Intensidad = 4
                        },
                        new
                        {
                            PlantaId = 7,
                            EfectoId = 7,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 8,
                            EfectoId = 3,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 9,
                            EfectoId = 7,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 10,
                            EfectoId = 5,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 11,
                            EfectoId = 1,
                            Intensidad = 4
                        },
                        new
                        {
                            PlantaId = 12,
                            EfectoId = 2,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 13,
                            EfectoId = 2,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 14,
                            EfectoId = 2,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 15,
                            EfectoId = 4,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 16,
                            EfectoId = 4,
                            Intensidad = 4
                        },
                        new
                        {
                            PlantaId = 17,
                            EfectoId = 2,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 18,
                            EfectoId = 1,
                            Intensidad = 4
                        },
                        new
                        {
                            PlantaId = 19,
                            EfectoId = 1,
                            Intensidad = 5
                        },
                        new
                        {
                            PlantaId = 20,
                            EfectoId = 1,
                            Intensidad = 4
                        },
                        new
                        {
                            PlantaId = 21,
                            EfectoId = 1,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 22,
                            EfectoId = 2,
                            Intensidad = 4
                        },
                        new
                        {
                            PlantaId = 23,
                            EfectoId = 1,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 24,
                            EfectoId = 5,
                            Intensidad = 4
                        },
                        new
                        {
                            PlantaId = 25,
                            EfectoId = 6,
                            Intensidad = 4
                        },
                        new
                        {
                            PlantaId = 26,
                            EfectoId = 3,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 27,
                            EfectoId = 1,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 28,
                            EfectoId = 6,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 28,
                            EfectoId = 7,
                            Intensidad = 3
                        },
                        new
                        {
                            PlantaId = 29,
                            EfectoId = 3,
                            Intensidad = 5
                        },
                        new
                        {
                            PlantaId = 30,
                            EfectoId = 3,
                            Intensidad = 4
                        });
                });

            modelBuilder.Entity("Templanza.Models.ReporteVentasItem", b =>
                {
                    b.Property<int>("CantidadVendida")
                        .HasColumnType("int");

                    b.Property<string>("NombreComun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantaId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalVendido")
                        .HasColumnType("decimal(12,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Templanza.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Templanza.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Templanza.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Templanza.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Templanza.Models.Blend", b =>
                {
                    b.HasOne("Templanza.Models.Categoria", "Categoria")
                        .WithMany("Blends")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Templanza.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Templanza.Models.BlendLike", b =>
                {
                    b.HasOne("Templanza.Models.Blend", "Blend")
                        .WithMany("BlendLikes")
                        .HasForeignKey("BlendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Templanza.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blend");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Templanza.Models.BlendPlanta", b =>
                {
                    b.HasOne("Templanza.Models.Blend", "Blend")
                        .WithMany("BlendPlantas")
                        .HasForeignKey("BlendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Templanza.Models.Planta", "Planta")
                        .WithMany("BlendPlantas")
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blend");

                    b.Navigation("Planta");
                });

            modelBuilder.Entity("Templanza.Models.Comentario", b =>
                {
                    b.HasOne("Templanza.Models.Blend", "Blend")
                        .WithMany("Comentarios")
                        .HasForeignKey("BlendId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Templanza.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blend");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Templanza.Models.ItemOrden", b =>
                {
                    b.HasOne("Templanza.Models.Orden", "Orden")
                        .WithMany("ItemOrdenes")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Templanza.Models.Planta", "Planta")
                        .WithMany("ItemOrdenes")
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orden");

                    b.Navigation("Planta");
                });

            modelBuilder.Entity("Templanza.Models.Orden", b =>
                {
                    b.HasOne("Templanza.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Templanza.Models.Planta", b =>
                {
                    b.HasOne("Templanza.Models.Categoria", "Categoria")
                        .WithMany("Plantas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Templanza.Models.PlantaEfecto", b =>
                {
                    b.HasOne("Templanza.Models.Efecto", "Efecto")
                        .WithMany("PlantaEfectos")
                        .HasForeignKey("EfectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Templanza.Models.Planta", "Planta")
                        .WithMany("PlantaEfectos")
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Efecto");

                    b.Navigation("Planta");
                });

            modelBuilder.Entity("Templanza.Models.Blend", b =>
                {
                    b.Navigation("BlendLikes");

                    b.Navigation("BlendPlantas");

                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("Templanza.Models.Categoria", b =>
                {
                    b.Navigation("Blends");

                    b.Navigation("Plantas");
                });

            modelBuilder.Entity("Templanza.Models.Efecto", b =>
                {
                    b.Navigation("PlantaEfectos");
                });

            modelBuilder.Entity("Templanza.Models.Orden", b =>
                {
                    b.Navigation("ItemOrdenes");
                });

            modelBuilder.Entity("Templanza.Models.Planta", b =>
                {
                    b.Navigation("BlendPlantas");

                    b.Navigation("ItemOrdenes");

                    b.Navigation("PlantaEfectos");
                });
#pragma warning restore 612, 618
        }
    }
}
